{{- define "ioc-instance.configmap" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "ioc-chart.release" . }}
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
data:
{{- if .Values.gitRepoConfig.enable }}
  url: {{ .Values.gitRepoConfig.url | quote }}
  branch: "{{.Values.gitRepoConfig.branch}}"
  path: {{ .Values.gitRepoConfig.path | quote }}
{{- end -}}
{{- end -}}
