{{- define "ioc-instance.configmap" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "ioc-chart.release" . }}
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
data:
{{- if .Values.iocGitRepoConfig.enable }}
  url: {{ .Values.iocGitRepoConfig.url | quote }}
  branch: {{.Values.iocGitRepoConfig.branch}}
  path: {{ .Values.iocGitRepoConfig.path | quote }}
{{- end -}}
{{- end -}}
