{{- define "ioc-instance.deployment" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ioc-chart.release" . }}
  labels:
    app: {{ include "ioc-chart.release" . }}
    chart: {{ include "ioc-chart.name" . }}
    beamline: {{ .Values.beamline | quote}}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ioc-chart.release" . }}
  template:
    metadata:
      labels:
        app: {{ include "ioc-chart.release" . }}
        beamline: {{ .Values.beamline | quote }}
        ioc_version: {{ .Values.ioc_version | quote }}
        chart: {{ include "ioc-chart.name" . }}
        is_ioc: "True"
        
        
    spec:
      {{ if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{ if and (.Values.iocGitRepoConfig.enable) (.Values.iocGitRepoConfig.url) }}
      initContainers:
      - name: init-volume
        image: alpine:latest
        command: 
        - sh 
        - -c
        - |
          apk --no-cache add git
        
          rm -rf /tmp/*
          if [ -n "{{ .Values.iocGitRepoConfig.branch }}" ];then
            git clone -b {{ .Values.iocGitRepoConfig.branch }} {{ .Values.iocGitRepoConfig.url }} --recurse-submodules temp-config
          else
            git clone {{ .Values.iocGitRepoConfig.url }} --recurse-submodules temp-config
          fi

          if [ -d temp-config/{{ .Values.iocGitRepoConfig.path}} ];then
            if [ "{{ .Values.iocGitRepoConfig.path }}" == "." ];then
                mv temp-config/* /tmp/
            else
              mv temp-config/{{ .Values.iocGitRepoConfig.path}}/* /tmp/
              rm -rf temp-config
            fi
          else
            mv temp-config/* /tmp/ /autosave
          fi

          chmod a+w,a+r -R /tmp
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
        - name: autosave-volume
          mountPath: /autosave
    {{ end }}
      terminationGracePeriodSeconds: 15 # nice to have quick restarts on IOCs
      volumes:
        {{- if .Values.runtimeClaim }}
        - name: runtime-volume
          persistentVolumeClaim:
            claimName: {{ .Values.runtimeClaim }}
        {{- end }}
        {{- if .Values.opisClaim }}
        - name: opis-volume
          persistentVolumeClaim:
            claimName: {{ .Values.opisClaim }}
        {{- end }}
        {{- if .Values.nfsv2TftpClaim }}
        - name: nfsv2-tftp-volume
          persistentVolumeClaim:
            claimName: {{ .Values.nfsv2TftpClaim }}
        {{- end }}
        
        - name: autosave-volume
          persistentVolumeClaim:
            {{- if .Values.autosave }}
            claimName: {{ .Values.autosave }}
            {{- else }}
            claimName: {{ include "ioc-chart.release" . }}-autosave-pvc
            {{- end }}
        {{- if .Values.dataVolume.pvc }}
        - name: {{ include "ioc-chart.release" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "ioc-chart.release" . }}-data
        {{- else if .Values.dataVolume.hostPath }}
        - name: {{ include "ioc-chart.release" . }}-data
          hostPath:
            path: {{ .Values.dataVolume.hostPath }}
            type: Directory
        {{- end }}
        {{- if and (.Values.iocGitRepoConfig.enable) (.Values.iocGitRepoConfig.url) }}
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ include "ioc-chart.release" . }}-config
        {{- else}}
        - name: config-volume
          configMap:
            name: {{ include "ioc-chart.release" . }}
        {{- end }}
      containers:
      - name: {{ include "ioc-chart.release" . }}
        image: {{ .Values.image }}
        command:
          - bash
        {{- if .Values.start }}
        args:
          - {{ .Values.start }}
        {{- end }}
        ports:
          - containerPort: 5064
          - containerPort: 5065
        {{- if .Values.liveness }}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - {{ .Values.liveness }}
          initialDelaySeconds: 120
          periodSeconds: 10
        {{- end }}
        {{- if .Values.stop }}

        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "{{ .Values.stop }}"]
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.iocConfig }}
        {{- if .Values.autosave }}
        - name: autosave-volume
          mountPath: /autosave
        {{- end }}
        {{- if or (.Values.dataVolume.pvc) (.Values.dataVolume.hostPath)  }}
        - name: {{ include "ioc-chart.release" . }}-data
          mountPath: {{ .Values.dataVolume.hostPath }}
          {{- if .Values.dataVolume.hostPath }}
          mountPropagation: HostToContainer
          {{- end}}
        {{- end }}
        {{- if .Values.nfsv2TftpClaim }}
        - name: nfsv2-tftp-volume
          mountPath: /nfsv2-tftp
          subPath: "{{ .Values.beamline }}/{{ include "ioc-chart.release" . }}"
          {{- end }}
        {{- if .Values.runtimeClaim }}
        - name: runtime-volume
          mountPath: /epics/runtime
          subPath: "{{ include "ioc-chart.release" . }}"
        {{- end }}
        {{- if .Values.opisClaim }}
        - name: opis-volume
          mountPath: /epics/opi
          subPath: "{{ include "ioc-chart.release" . }}"
        {{- end }}
        stdin: true
        tty: true
        securityContext:
{{  toYaml .Values.securityContext | indent 10}}
        resources:
{{  toYaml .Values.resources | indent 10}}
        imagePullPolicy: Always
        env:
        - name: IOCSH_PS1
          value: "{{ include "ioc-chart.release" . }} > "
        - name: IOC_NAME
          value: "{{ .Release.Name }}"
        - name: IOC_PREFIX
          value: {{ or .Values.prefix .Release.Name | quote }}
        - name: IOC_VERSION
          value: {{ .Values.ioc_version | quote }}
        {{- range $envVar := .Values.env }}
        - name: {{ $envVar.name }}
          value: {{ $envVar.value | quote }}
        {{- end }}
        {{- range $envVar := .Values.globalenv }}
        - name: {{ $envVar.name }}
          value: {{ $envVar.value | quote }}
        {{- end }}
      {{- if .Values.useAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - {{ .Values.beamline }}
      {{- end }}
      tolerations:
        - key: nodetype
          operator: Equal
          value: {{ .Values.beamline }}
          effect: NoSchedule

---
{{- end -}}
