{{- define "ioc-instance.service" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "ioc-chart-chart.release" . }}-service
spec:
  selector:
    app: {{ include "ioc-chart-chart.release" . }}
    beamline: {{ .Values.beamline }}
    chart: {{ .Chart.Name }}

  ports:
  - name: ca-port0-tcp
    port: 5064  # 
    targetPort: 5064  # 
    protocol: TCP
  - name: ca-port0-udp
    port: 5064  # 
    targetPort: 5064  # 
    protocol: UDP
  - name: ca-port1-tcp
    port: 5065  # 
    targetPort: 5065  # 
    protocol: TCP
  - name: ca-port1-udp
    port: 5065  #
    targetPort: 5065  # 
    protocol: UDP
  


---
{{- end -}}
