# IOCS can use a PVC as a data volume, or mount the host filesystem
{{- define "ioc-instance.volume" -}}

{{- if .Values.dataVolume.pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ioc-chart.release" . }}-data
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
spec:
  accessModes:
    - {{ .Values.dataVolume.accessMode }}
  resources:
    requests:
      storage: 1000Mi

---
{{- end }}
{{ if and (.Values.iocGitRepoConfig.enable) (.Values.iocGitRepoConfig.url) }}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ioc-chart.release" . }}-config
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
{{- end }}
{{- if not .Values.autosaveClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ioc-chart.release" . }}-autosave
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end }}
{{- end }}

