
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "ioc-chart.release" . }}
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
data:
{{- if .Values.gitRepoConfig.url }}
  url: {{ .Values.gitRepoConfig.url }}
  branch: "{{.Values.gitRepoConfig.branch}}"
  path: {{ .Values.gitRepoConfig.path | quote }}
{{- else}}
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
{{- end }}
  
