
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "ioc-chart.release" . }}
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
data:
  config.yaml: |
    {{ toYaml .Values | indent 4 }}

  
