apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ioc-chart.release" . }}
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
data:
  config.yaml: |
    {{- if .Values.nfsMounts }}
    {{- range .Values.nfsMounts }}
    {{ .name | lower }}_dir: {{ .mountPath }}/{{ $.Values.iocname }}
    {{- end }}
    {{- else }}
    config_dir: {{ .Values.iocConfig }}
    data_dir: {{.Values.dataVolume.hostPath}}
    autosave_dir: "/autosave"
    {{- end }}
    {{- if .Values.workdir }}
    ioctop: {{.Values.workdir}}
    {{- else }}
    ioctop: {{.Values.iocConfig}}
    {{- end }}
    {{- if .Values.epicsConfiguration.iocparam }}
    {{- range .Values.epicsConfiguration.iocparam }}
    {{ .name }}: {{ .value }}
    {{- end }}
    {{- end }}
    {{- range .Values.iocparam }}
    {{.name}}: {{.value}}
    {{- end}}
{{ toYaml .Values | indent 4 }}