apiVersion: v1
kind: Service
metadata:
  name: {{ include "ioc-chart.release" . }}
spec:
  selector:
    {{- include "ioc-chart.selectorLabels" . | nindent 4 }}

  ports:
  - name: ca-port0-tcp
    port: 5064  # 
    targetPort: 5064  # 
    protocol: TCP
  - name: ca-port0-udp
    port: 5064  # 
    targetPort: 5064  # 
    protocol: UDP
  - name: ca-port1-tcp
    port: 5065  # 
    targetPort: 5065  # 
    protocol: TCP
  - name: ca-port1-udp
    port: 5065  #
    targetPort: 5065  # 
    protocol: UDP

