{{- if .Values.ingress.enabled }}
{{- $fullName := include "ioc-chart.release" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ioc-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if hasKey .Values.service "port" }}
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          {{- if and .Values.service.http.enable (hasKey .Values.service.http "port") }}
          - path: /web
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.http.port }}
          {{- end }}
    {{- end }}
{{- end }}
