{{- if .Values.ingress.enabled }}
{{- $fullName := include "ioc-chart.release" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ioc-chart.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "haproxy"}}
    haproxy.org/path-rewrite: /web/(.*) /\1
    {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /web/(.*) /$1
    {{- end}}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if hasKey $.Values.service "port" }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
          {{- if and $.Values.service.http.enable (hasKey $.Values.service.http "port") }}
          - path:  /web
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end }}
