# IOCS can use a PVC as a data volume, or mount the host filesystem

{{- if .Values.dataVolume.pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ioc-chart.release" . }}-data
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline | quote }}
spec:
  accessModes:
    - {{ .Values.dataVolume.accessMode }}
  {{- if .Values.securityContext.runAsGroup }}
  fsGroup: {{ .Values.securityContext.runAsGroup }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.dataVolume.size }}

---
{{- end }}
{{ if .Values.gitRepoConfig.url }}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ioc-chart.release" . }}-gitconfig
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.securityContext.runAsGroup }}
  fsGroup: {{ .Values.securityContext.runAsGroup }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gitRepoConfig.size }}
---
{{- end }}
{{- if not .Values.autosaveClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ioc-chart.release" . }}-autosave
  labels:
    app: {{ include "ioc-chart.release" . }}
    beamline: {{ .Values.beamline | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.securityContext.runAsGroup }}
  fsGroup: {{ .Values.securityContext.runAsGroup }}
  {{- end }}
  resources:
    requests:
      storage: 1Gi
{{- end }}

